apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudvault-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudvault-agent
spec:
  selector:
    matchLabels:
      app: cloudvault-agent
  template:
    metadata:
      annotations:
        rollout.force: {{ now | quote }}
      labels:
        app: cloudvault-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cloudvault-agent"]
          args:
            - "--interval={{ .Values.agent.interval }}"
            - "--timescale={{ .Values.agent.timescale_conn }}"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "NET_ADMIN"]
          volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
          env:
            - name: TIMESCALE_CONN
              value: {{ .Values.agent.timescale_conn | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLOUDVAULT_AI_URL
              value: "http://{{ include "cloudvault.fullname" . }}-ai.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.ai.service.port }}"
            - name: PROMETHEUS_URL
              {{- if .Values.prometheus.enabled }}
              value: "http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local:80"
              {{- else }}
              value: "http://prometheus-server.monitoring.svc.cluster.local:80"
              {{- end }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      volumes:
        - name: bpf-maps
          hostPath:
            path: /sys/fs/bpf
            type: Directory
