apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvault-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudvault-dashboard
spec:
  replicas: {{ .Values.dashboard.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudvault-dashboard
  template:
    metadata:
      annotations:
        rollout.force: {{ now | quote }}
      labels:
        app: cloudvault-dashboard
    spec:
      hostPID: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: dashboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/cloudvault", "dashboard"]
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: ["SYS_ADMIN", "NET_ADMIN", "NET_RAW", "SYS_RESOURCE"]
          volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
          resources:
            {{- toYaml .Values.dashboard.resources | nindent 12 }}
          env:
            - name: PROMETHEUS_URL
              {{- if .Values.prometheus.enabled }}
              value: "http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local:80"
              {{- else }}
              value: "http://prometheus-server.monitoring.svc.cluster.local:80"
              {{- end }}
            - name: CLOUDVAULT_ADMIN_USER
              value: "admin"
            - name: CLOUDVAULT_ADMIN_PASSWORD
              value: "cloudvault-secret"
            - name: CLOUDVAULT_AI_URL
              value: "http://{{ include "cloudvault.fullname" . }}-ai.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.ai.service.port }}"
      volumes:
        - name: bpf-maps
          hostPath:
            path: /sys/fs/bpf
            type: Directory
