package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"math/rand"
	"net/http"
	"os"
	"time"
)

func main() {
	generateCmd := flag.NewFlagSet("generate", flag.ExitOnError)
	count := generateCmd.Int("count", 100, "Number of PVCs to generate")
	start := generateCmd.Int("start", 0, "Starting index for naming")

	monitorCmd := flag.NewFlagSet("monitor", flag.ExitOnError)
	url := monitorCmd.String("url", "http://localhost:8080/api/pvc", "URL to monitor")

	if len(os.Args) < 2 {
		fmt.Println("expected 'generate' or 'monitor' subcommands")
		os.Exit(1)
	}

	switch os.Args[1] {
	case "generate":
		_ = generateCmd.Parse(os.Args[2:])
		generate(*count, *start)
	case "monitor":
		_ = monitorCmd.Parse(os.Args[2:])
		monitor(*url)
	default:
		fmt.Println("expected 'generate' or 'monitor' subcommands")
		os.Exit(1)
	}
}

func generate(count, start int) {
	storageClasses := []string{"standard", "gp3", "io1", "slow"}
	fmt.Println("# Generated by cloudvault-stress")

	for i := 0; i < count; i++ {
		idx := start + i
		sc := storageClasses[rand.Intn(len(storageClasses))]
		size := rand.Intn(100) + 1

		pvcYAML := fmt.Sprintf(`
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stress-pvc-%d
  namespace: default
  labels:
    app: stress-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: %s
  resources:
    requests:
      storage: %dGi
---
apiVersion: v1
kind: Pod
metadata:
  name: stress-pod-%d
  namespace: default
  labels:
    app: stress-test
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
    volumeMounts:
    - mountPath: "/data"
      name: stress-vol
  volumes:
    - name: stress-vol
      persistentVolumeClaim:
        claimName: stress-pvc-%d
---`, idx, sc, size, idx, idx)
		fmt.Print(pvcYAML)
	}
}

func monitor(url string) {
	fmt.Printf("Monitoring %s...\n", url)
	client := &http.Client{Timeout: 10 * time.Second}

	for {
		start := time.Now()
		resp, err := client.Get(url)
		duration := time.Since(start)

		if err != nil {
			fmt.Printf("❌ Error: %v\n", err)
		} else {
			var result []interface{}
			_ = json.NewDecoder(resp.Body).Decode(&result)
			_ = resp.Body.Close()
			fmt.Printf("✅ Count: %d | Latency: %v\n", len(result), duration)
		}

		time.Sleep(2 * time.Second)
	}
}
