//go:build linux

package ebpf

import (
	"io"

	"github.com/cilium/ebpf"
)

// The following types are normally generated by bpf2go.
// We provide them here as placeholders to satisfy the compiler/IDE
// when the generated artifacts are missing.

type egressObjects struct {
	EgressMap    *ebpf.Map
	EgressFilter *ebpf.Program
	io.Closer
}

func (o *egressObjects) Close() error { return nil }

type egressEgressStats struct {
	Bytes uint64
}

func loadEgressObjects(obj interface{}, opts interface{}) error {
	return nil
}
