//go:build linux

package ebpf

import (
	"io"

	"github.com/cilium/ebpf/link"
)

// The following types are normally generated by bpf2go.
// We provide them here as placeholders to satisfy the compiler/IDE
// when the generated artifacts are missing.

type egressObjects struct {
	EgressMap    *ebpfMap
	EgressFilter *ebpfProgram
	io.Closer
}

func (o *egressObjects) Close() error { return nil }

type ebpfMap struct{}
type ebpfProgram struct{}

func (m *ebpfMap) Iterate() *ebpfIter { return &ebpfIter{} }

type ebpfIter struct{}

func (i *ebpfIter) Next(key interface{}, val interface{}) bool { return false }
func (i *ebpfIter) Err() error                                 { return nil }

type egressEgressStats struct {
	Bytes uint64
}

func loadEgressObjects(obj interface{}, opts interface{}) error {
	return nil
}

// SocketOptions stub
type SocketOptions struct {
	Program *ebpfProgram
	Target  int
}

func AttachSocket(opts SocketOptions) (Link, error) {
	return nil, nil
}

type Link interface {
	Close() error
	Update(Program interface{}) error
	Pin(string) error
	Unpin() error
	Detach() error
	Info() (*link.Info, error)
}
