//go:build linux

package ebpf

import (
	"io"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// The following types are normally generated by bpf2go.
// We provide them here as placeholders to satisfy the compiler/IDE
// when the generated artifacts are missing.

type egressObjects struct {
	EgressMap    *ebpf.Map
	EgressFilter *ebpf.Program
	io.Closer
}

func (o *egressObjects) Close() error { return nil }

type egressEgressStats struct {
	Bytes uint64
}

func loadEgressObjects(obj interface{}, opts interface{}) error {
	return nil
}

// SocketOptions stub
type SocketOptions struct {
	Program *ebpf.Program
	Target  int
}

func AttachSocket(opts SocketOptions) (link.Link, error) {
	return nil, nil
}
